SELECT * FROM ALL_TABLES;

CREATE TABLE USERINFO(
	USERID VARCHAR(20) PRIMARY KEY, 
	USERNAME VARCHAR(25),
	USERPW VARCHAR(20),
	UDATE DATE
);

INSERT INTO USERINFO VALUES ('timo','티모','1234',SYSDATE);
INSERT INTO USERINFO VALUES ('an','ykouo','11',SYSDATE);
SELECT * FROM USERINFO;
-- ================================================================================================

CREATE TABLE MESSAGE(
	MID INT PRIMARY KEY, 
	USERID VARCHAR(20),
	MSG VARCHAR(100),
	FAVCOUNT INT DEFAULT 0,
	REPLYCOUNT INT DEFAULT 0,
	MDATE DATE
);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','1번글',1,2,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','2번글',2,3,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','3번글',2,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'an','4번글',2,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'an','5번글',3,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'an','6번글',1,0,SYSDATE);

SELECT * FROM MESSAGE WHERE USERID ='an';
SELECT * FROM MESSAGE WHERE ROWNUM <= 5 ORDER BY MID DESC ;
-- ================================================================================================

CREATE TABLE REPLY(
	RID INT PRIMARY KEY, 
	MID INT, 
	USERID VARCHAR(20),
	RDATE DATE,
	RMSG VARCHAR(50),
	CONSTRAINT MSGRP FOREIGN KEY (MID) REFERENCES MESSAGE (MID) ON DELETE CASCADE
);

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),1,'timo',SYSDATE,'대댓글1');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),1,'timo',SYSDATE,'대댓글2');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'대댓글3');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'대댓글4');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'대댓글5');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),?,?,SYSDATE,?)
-- ================================================================================================

SELECT * FROM MESSAGE WHERE ROWNUM <= 6 ORDER BY MID DESC;

UPDATE MESSAGE SET REPLYCOUNT=REPLYCOUNT-1 WHERE MID=1;
SELECT * FROM REPLY;
SELECT * FROM MESSAGE;
SELECT COUNT(*) AS CNT FROM MESSAGE;
SELECT * FROM USERINFO;
select * from reply;
DROP TABLE USERINFO;
DROP TABLE REPLY;
DROP TABLE MESSAGE;
DELETE FROM MESSAGE WHERE MID>=1 AND MID<=50;
DELETE FROM REPLY WHERE RID>=1 AND RID<=3;
DELETE FROM USERINFO WHERE USERID='an';
SELECT * FROM MESSAGE ((SELECT * FROM MESSAGE WHERE USERID =?))