select * from all_tables;

CREATE TABLE MEM(
	MNUM INT PRIMARY KEY,
	MID VARCHAR(30) NOT NULL,
	MPW VARCHAR(30) NOT NULL
);
	
INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'an','11');
INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'kim','1234');
INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'jan','0918');
INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'love','3333');
