select * from all_tables;

CREATE TABLE MEM(
	MNUM INT PRIMARY KEY,
	MID VARCHAR(50) NOT NULL,
	MNAME VARCHAR(50) NOT NULL,
	MPW VARCHAR(50) NOT NULL
);

SELECT * FROM MEM;

DROP TABLE MEM;

INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'an','ykouo','11');
INSERT INTO MEM VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEM),'jan','jandi','22');

DELETE FROM MEM WHERE MID='jan' and MPW='22';

CREATE TABLE POST(
	PNUM INT PRIMARY KEY,
	PTITLE VARCHAR(50) NOT NULL,
	PWRITER VARCHAR(50) NOT NULL,
	PCONTENT VARCHAR(300) NOT NULL,
	PDATE DATE DEFAULT SYSDATE
);

SELECT * FROM POST ORDER BY PNUM DESC;

DROP TABLE POST;

INSERT INTO POST VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM POST),'WELCOME','ykouo','Welcome! Nice to meet you',SYSDATE);
INSERT INTO POST VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM POST),'HELLO','ykouo','Welcome! Nice to meet you',SYSDATE);
INSERT INTO POST VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM POST),'NICE TO MEET YOU','jandi','Welcome! Nice to meet you',SYSDATE);
INSERT INTO POST VALUES ((SELECT NVL(MAX(PNUM),0)+1 FROM POST),'love','ykouo','Welcome! Nice to meet you',SYSDATE);

UPDATE POST SET PTITLE=?,PCONTENT=? WHERE MNUM=?

UPDATE MEM SET MID=?, MNAME=?, MPW=? WHERE MNUM=?
