SELECT * FROM ALL_TABLES;

CREATE TABLE USERINFO(
	USERID VARCHAR(20) PRIMARY KEY, 
	USERNAME VARCHAR(25),
	USERPW VARCHAR(20),
	UDATE DATE
);

INSERT INTO USERINFO VALUES ('timo','Æ¼¸ð','1234',SYSDATE);
INSERT INTO USERINFO VALUES ('an','ykouo','11',SYSDATE);
SELECT * FROM USERINFO;
-- ================================================================================================

CREATE TABLE MESSAGE(
	MID INT PRIMARY KEY, 
	USERID VARCHAR(20),
	MSG VARCHAR(100),
	FAVCOUNT INT DEFAULT 0,
	REPLYCOUNT INT DEFAULT 0,
	MDATE DATE
);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','±ÛÀÛ¼º',1,2,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','¡Ú¡Ú¡Ú¡Ú¡Ú',2,3,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','È®ÀÎ1',2,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'timo','È®ÀÎ2',2,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'an','¾È³ç',3,0,SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MID),0)+1 FROM MESSAGE),'an','hellow',1,0,SYSDATE);

SELECT * FROM MESSAGE WHERE USERID ='an';
SELECT * FROM MESSAGE WHERE ROWNUM <= 5 ORDER BY MID DESC ;
-- ================================================================================================

CREATE TABLE REPLY(
	RID INT PRIMARY KEY, 
	MID INT, 
	USERID VARCHAR(20),
	RDATE DATE,
	RMSG VARCHAR(50),
	CONSTRAINT MSGRP FOREIGN KEY (MID) REFERENCES MESSAGE (MID) ON DELETE CASCADE
);

INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),1,'timo',SYSDATE,'´ë´ñ±Û1');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),1,'timo',SYSDATE,'´ë´ñ±Û2');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'´ë´ñ±Û3');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'´ë´ñ±Û4');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),2,'timo',SYSDATE,'´ë´ñ±Û5');
INSERT INTO REPLY VALUES((SELECT NVL(MAX(RID),0)+1 FROM REPLY),?,?,SYSDATE,?)
-- ================================================================================================

SELECT * FROM REPLY;
SELECT * FROM MESSAGE;
SELECT * FROM USERINFO;
select * from reply;

DELETE FROM MESSAGE WHERE MID>=1 AND MID<=41;
DELETE FROM USERINFO WHERE USERID='an';
SELECT * FROM MESSAGE ((SELECT * FROM MESSAGE WHERE USERID =?))