SELECT * FROM ALL_TABLES;

DROP TABLE MESSAGE;
DROP TABLE MEMBER;

CREATE TABLE MESSAGE(
	MNUM INT PRIMARY KEY, 
	WRITER VARCHAR(30) NOT NULL,
	TITLE VARCHAR(30) NOT NULL,
	CONTENT VARCHAR(150) NOT NULL,
	WDATE DATE DEFAULT SYSDATE
);
SELECT *FROM MESSAGE;
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MESSAGE),'SIRI','SIRI¾ß','WELCOME',SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MESSAGE),'java','java','hello world',SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MESSAGE),'python','python','hellow ptyhon',SYSDATE);
INSERT INTO MESSAGE VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MESSAGE),'siri','SIRI¾ß','WELCOME',SYSDATE);

create table member(
   mnum int primary key ,
    mid varchar(15),
    mpw varchar(15)
);
INSERT INTO MEMBER VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEMBER),'an','11');
INSERT INTO MEMBER VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEMBER),'co','11');
INSERT INTO MEMBER VALUES ((SELECT NVL(MAX(MNUM),0)+1 FROM MEMBER),'ra','11');
SELECT *FROM MEMBER;