



CREATE TABLE ABANK(
	BID INT PRIMARY KEY, 
	NAME VARCHAR(20),
	BALANCE INT
);

CREATE TABLE BBANK(
	BID INT PRIMARY KEY, 
	NAME VARCHAR(20),
	BALANCE INT
);
INSERT INTO ABANK VALUES (1001,'ARI',10000);
INSERT INTO BBANK VALUES (2001,'DONGDONG',5000);




CREATE TABLE BANK(
	BID INT PRIMARY KEY, 
	NAME VARCHAR(20),
	BALANCE INT
);

INSERT INTO BANK VALUES (1001,'ARI',10000);
INSERT INTO BANK VALUES (2001,'DONGDONG',5000);

select * from bank;