SELECT * FROM ALL_TABLES;

CREATE TABLE TEST(
	NAME VARCHAR(20),
	EMAIL VARCHAR(30),
	uid varchar
);

INSERT INTO TEST VALUES('an', 'co11@naver.com');
INSERT INTO TEST VALUES('y', 'y500@naver.com');
INSERT INTO TEST VALUES('k', 'ouo333@naver.com');

SELECT * FROM TEST;

DROP TABLE MEMBER;
TEST

CREATE TABLE MEMBER(
	NAME VARCHAR(50) PRIMARY KEY,
	UID VARCHAR(50) NOT NULL,
	UPW VARCHAR(50) NOT NULL
);

SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES ('ayk','a','11');


